name = "ILUK"
uuid = "8b5b43b3-c2f7-49eb-97b3-de4a4853213c"
authors = ["tunnellm <tunnellm@mail.gvsu.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparseMatrixCollection = "ac199af8-68bc-55b8-82c4-7abd6f96ed98"

[compat]
MatrixMarket = "0.5.2"
SuiteSparseMatrixCollection = "0.5.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
